name: 마곡나루 매장 맞춤 추천 봇

on:
  workflow_dispatch:
    inputs:
      user_message:
        description: '알고 싶은 마곡나루 매장명을 입력하세요 (예: 샐러디 추천해줘)'
        required: true
        default: '샐러디'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: 깃허브 코드 가져오기
      uses: actions/checkout@v4

    - name: 파이썬 설치하기
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 필수 도구 자동 설치
      run: pip install requests

    - name: 샐러드 봇 실행하기
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        USER_MESSAGE: ${{ github.event.inputs.user_message }} # 👈 내가 입력한 글자를 파이썬으로 토스
      run: python salad_bot.py
